export const productos = [
    {
        id: 1,
        nombre: "mate imperial",
        precio: 25000,
        categoria: "Mates",
        stock: 11,
        descripcion: "mate de calabaza con virola de acero",
        img: "",
    },
    {
        id: 2,
        nombre: "Mate torpedo",
        precio: 32000,
        categoria: "Mates",
        stock: 14,
        descripcion: "mate torpedo con virola de alpaca cincelada",
        img: "",
    },
    {
        id: 3,
        nombre: "termo stanley",
        precio: 120000,
        categoria: "Termos",
        stock: 9,
        descripcion: "termo de la mas alta calidad",
        img: "",
    },
    {
        id: 4,
        nombre: "termo lumilagro",
        precio: 17000,
        categoria: "Termos",
        stock: 12,
        descripcion: "termo de acero inox",
        img: "",
    },
    {
        id: 5,
        nombre: "Mate camionero",
        precio: 15000,
        categoria: "Mates",
        stock: 8,
        descripcion: "mate camionero con virola de acero",
        img: "",
    },
];